// src/reminders/temporal.js — Reminder date/time semantics shared by UI, notes, and tests
// Auto-generated by split script. Edit here, then run ./build-main.sh

function padReminderTimePart(value) {
    var n = Number(value);
    if (!isFinite(n)) n = 0;
    return String(Math.max(0, Math.min(99, n))).padStart(2, "0");
}

function normalizeReminderDueTime(value) {
    if (value == null) return "";
    var raw = String(value).trim();
    var match = raw.match(/^(\d{1,2}):(\d{2})$/);
    if (!match) return raw;
    return padReminderTimePart(match[1]) + ":" + padReminderTimePart(match[2]);
}

function reminderHasDueTime(rem) {
    if (!rem) return false;
    if (rem.hasDueTime === true) return true;
    if (rem.hasDueTime === false) return false;
    return !!normalizeReminderDueTime(rem.dueTime || "");
}

function coerceReminderDate(value) {
    if (!value) return null;
    if (value instanceof Date) return isFinite(value.getTime()) ? value : null;
    var d = new Date(value);
    return isFinite(d.getTime()) ? d : null;
}

function normalizeReminderTemporalFields(rem) {
    var source = rem || {};
    var due = coerceReminderDate(source.due) || coerceReminderDate(source.dueDate);
    var dueTime = normalizeReminderDueTime(source.dueTime || "");
    var hasDueTime = source.hasDueTime === true || (source.hasDueTime !== false && !!dueTime);
    if (!hasDueTime) dueTime = "";

    var normalized = Object.assign({}, source, {
        due: due,
        dueDate: source.dueDate || (due ? due.toISOString() : ""),
        dueTime: dueTime,
        hasDueTime: hasDueTime
    });
    return normalized;
}

function isSameLocalDay(a, b) {
    if (!a || !b) return false;
    return a.getFullYear() === b.getFullYear() &&
        a.getMonth() === b.getMonth() &&
        a.getDate() === b.getDate();
}

function formatLocalReminderDate(d) {
    if (!d) return "";
    return (d.getMonth() + 1) + "/" + d.getDate();
}

function formatLocalReminderTime(d, rem) {
    var explicit = normalizeReminderDueTime(rem && rem.dueTime);
    if (explicit) return explicit;
    if (!d) return "";
    return d.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", hour12: false });
}

function formatReminderDueText(rem, now) {
    var normalized = normalizeReminderTemporalFields(rem);
    var due = normalized.due;
    if (!due) return "";
    var current = now instanceof Date ? now : new Date();
    var dateText = isSameLocalDay(due, current) ? "Today" : formatLocalReminderDate(due);
    if (!reminderHasDueTime(normalized)) return dateText;
    var timeText = formatLocalReminderTime(due, normalized);
    return isSameLocalDay(due, current) ? timeText : (dateText + " " + timeText);
}

if (typeof module !== "undefined" && module.exports) {
    module.exports = {
        coerceReminderDate: coerceReminderDate,
        formatReminderDueText: formatReminderDueText,
        isSameLocalDay: isSameLocalDay,
        normalizeReminderDueTime: normalizeReminderDueTime,
        normalizeReminderTemporalFields: normalizeReminderTemporalFields,
        reminderHasDueTime: reminderHasDueTime
    };
}
