// src/macos/notifications.js — In-app notification helpers and MacOSIntegration prototype methods
// Auto-generated by split script. Edit here, then run ./build-main.sh

function getNotificationSettings(options) {
    var opts = options || {};
    var lead = Number(opts.notificationLeadMinutes);
    if (!isFinite(lead) || lead < 1) lead = 10;
    if (lead > 1440) lead = 1440;
    return {
        notificationsEnabled: opts.notificationsEnabled === true,
        eventNotificationsEnabled: opts.eventNotificationsEnabled !== false,
        reminderNotificationsEnabled: opts.reminderNotificationsEnabled !== false,
        notificationLeadMinutes: lead,
        previousDayNotificationsEnabled: opts.previousDayNotificationsEnabled !== false,
        previousDayNotificationTime: normalizeNotificationClockTime(opts.previousDayNotificationTime || "18:00")
    };
}

function normalizeNotificationClockTime(value) {
    var raw = String(value || "").trim();
    var match = raw.match(/^(\d{1,2}):(\d{2})$/);
    if (!match) return "18:00";
    var h = Math.max(0, Math.min(23, Number(match[1])));
    var m = Math.max(0, Math.min(59, Number(match[2])));
    return String(h).padStart(2, "0") + ":" + String(m).padStart(2, "0");
}

function getNotificationItemId(type, item, phase, key) {
    var rawId = item && item.id ? String(item.id) : "";
    if (!rawId) return "";
    return type + ":" + rawId + ":" + phase + ":" + key;
}

function notificationWasDelivered(delivered, id) {
    return !!(delivered && id && delivered[id]);
}

function recordNotificationDelivery(delivered, id, now) {
    if (!delivered || !id) return;
    delivered[id] = (now || new Date()).toISOString();
}

function pruneNotificationDelivery(delivered, now) {
    if (!delivered) return;
    var cutoff = (now || new Date()).getTime() - 48 * 60 * 60 * 1000;
    Object.keys(delivered).forEach(function(id) {
        var t = new Date(delivered[id]).getTime();
        if (!isFinite(t) || t < cutoff) delete delivered[id];
    });
}

function getLocalDateKey(date) {
    if (!date) return "";
    return date.getFullYear() + "-" +
        String(date.getMonth() + 1).padStart(2, "0") + "-" +
        String(date.getDate()).padStart(2, "0");
}

function getLocalDayStart(date) {
    return new Date(date.getFullYear(), date.getMonth(), date.getDate(), 0, 0, 0, 0);
}

function getPreviousDayTriggerTime(targetDate, clockTime) {
    var parts = normalizeNotificationClockTime(clockTime).split(":");
    return new Date(
        targetDate.getFullYear(),
        targetDate.getMonth(),
        targetDate.getDate() - 1,
        Number(parts[0]),
        Number(parts[1]),
        0,
        0
    );
}

function shouldNotifyPreviousDay(now, targetDate, options) {
    if (!options.previousDayNotificationsEnabled || !targetDate) return false;
    var targetDayStart = getLocalDayStart(targetDate);
    var trigger = getPreviousDayTriggerTime(targetDate, options.previousDayNotificationTime);
    return now.getTime() >= trigger.getTime() && now.getTime() < targetDayStart.getTime();
}

function notificationReminderHasDueTime(rem) {
    if (typeof reminderHasDueTime === "function") return reminderHasDueTime(rem);
    if (!rem) return false;
    if (rem.hasDueTime === true) return true;
    if (rem.hasDueTime === false) return false;
    return !!(rem.dueTime && String(rem.dueTime).trim());
}

function pushNotificationCandidate(candidates, delivered, candidate) {
    if (!candidate || !candidate.id || notificationWasDelivered(delivered, candidate.id)) return;
    candidates.push(candidate);
}

function buildNotificationCandidates(input) {
    var now = input && input.now ? input.now : new Date();
    var options = getNotificationSettings(input && input.options);
    var delivered = (input && input.delivered) || {};
    var events = (input && input.events) || [];
    var reminders = (input && input.reminders) || [];
    var candidates = [];

    if (!options.notificationsEnabled) return candidates;

    if (options.eventNotificationsEnabled) {
        var leadMs = options.notificationLeadMinutes * 60 * 1000;
        events.forEach(function(evt) {
            if (!evt || !evt.start) return;
            var isAllDay = evt.isAllDay !== undefined ? evt.isAllDay : evt.allday;
            var start = evt.start instanceof Date ? evt.start : new Date(evt.start);
            if (!isFinite(start.getTime())) return;
            var title = evt.title || evt.summary || "Event";
            var targetKey = getLocalDateKey(start);
            if (shouldNotifyPreviousDay(now, start, options)) {
                pushNotificationCandidate(candidates, delivered, {
                    id: getNotificationItemId("event", evt, "previous-day", targetKey),
                    type: "event",
                    phase: "previous-day",
                    itemId: evt.id,
                    title: title,
                    message: title + " is tomorrow"
                });
            }
            if (isAllDay) return;
            var diff = start.getTime() - now.getTime();
            if (!isFinite(diff) || diff <= 0 || diff > leadMs) return;
            var minutes = Math.max(1, Math.ceil(diff / 60000));
            pushNotificationCandidate(candidates, delivered, {
                id: getNotificationItemId("event", evt, "lead", start.toISOString()),
                type: "event",
                phase: "lead",
                itemId: evt.id,
                title: title,
                message: title + " starts in " + minutes + " minute" + (minutes === 1 ? "" : "s")
            });
        });
    }

    if (options.reminderNotificationsEnabled) {
        reminders.forEach(function(rem) {
            if (!rem || !rem.due || rem.completed) return;
            var due = rem.due instanceof Date ? rem.due : new Date(rem.due);
            if (!isFinite(due.getTime())) return;
            var title = rem.title || rem.name || "Reminder";
            var dueDateKey = getLocalDateKey(due);
            var hasDueTime = notificationReminderHasDueTime(rem);
            if (shouldNotifyPreviousDay(now, due, options)) {
                pushNotificationCandidate(candidates, delivered, {
                    id: getNotificationItemId("reminder", rem, "previous-day", dueDateKey),
                    type: "reminder",
                    phase: "previous-day",
                    itemId: rem.id,
                    title: title,
                    message: title + " is due tomorrow"
                });
            }
            if (!hasDueTime) {
                var nowDay = getLocalDayStart(now);
                var dueDay = getLocalDayStart(due);
                if (dueDay.getTime() === nowDay.getTime()) {
                    pushNotificationCandidate(candidates, delivered, {
                        id: getNotificationItemId("reminder", rem, "today", dueDateKey),
                        type: "reminder",
                        phase: "today",
                        itemId: rem.id,
                        title: title,
                        message: title + " is due today"
                    });
                } else if (dueDay.getTime() < nowDay.getTime()) {
                    pushNotificationCandidate(candidates, delivered, {
                        id: getNotificationItemId("reminder", rem, "overdue", getLocalDateKey(now)),
                        type: "reminder",
                        phase: "overdue",
                        itemId: rem.id,
                        title: title,
                        message: title + " is overdue"
                    });
                }
                return;
            }
            var diff = due.getTime() - now.getTime();
            if (!isFinite(diff)) return;
            if (diff > 0 && diff <= (options.notificationLeadMinutes * 60 * 1000)) {
                pushNotificationCandidate(candidates, delivered, {
                    id: getNotificationItemId("reminder", rem, "lead", due.toISOString()),
                    type: "reminder",
                    phase: "lead",
                    itemId: rem.id,
                    title: title,
                    message: title + " is due in " + Math.max(1, Math.ceil(diff / 60000)) + " minute" + (Math.ceil(diff / 60000) === 1 ? "" : "s")
                });
            } else if (diff <= 0) {
                pushNotificationCandidate(candidates, delivered, {
                    id: getNotificationItemId("reminder", rem, "overdue", getLocalDateKey(now)),
                    type: "reminder",
                    phase: "overdue",
                    itemId: rem.id,
                    title: title,
                    message: title + " is overdue"
                });
            }
        });
    }

    return candidates;
}

function canUseObsidianNotice(obsidianRef) {
    return !!(obsidianRef && typeof obsidianRef.Notice === "function");
}

if (typeof MacOSIntegration !== "undefined") {
    MacOSIntegration.prototype.notifyDueItems = function(now) {
        var settings = getNotificationSettings(this.plugin.options || {});
        if (!settings.notificationsEnabled) {
            this._notificationStatus = "disabled";
            return [];
        }
        if (!canUseObsidianNotice(typeof obsidian !== "undefined" ? obsidian : null)) {
            this._notificationStatus = "unavailable";
            this._lastNotificationError = "Obsidian Notice API is unavailable";
            return [];
        }

        var checkedAt = now || new Date();
        pruneNotificationDelivery(this._deliveredNotifications, checkedAt);
        var candidates = buildNotificationCandidates({
            now: checkedAt,
            options: this.plugin.options || {},
            events: this.allEvents || [],
            reminders: this.allReminders || [],
            delivered: this._deliveredNotifications || {}
        });

        for (var i = 0; i < candidates.length; i++) {
            try {
                new obsidian.Notice(candidates[i].message, 8000);
                recordNotificationDelivery(this._deliveredNotifications, candidates[i].id, checkedAt);
            } catch (err) {
                this._notificationStatus = "error";
                this._lastNotificationError = err && err.message ? err.message : String(err);
                return candidates.slice(0, i);
            }
        }

        this._notificationStatus = "ok";
        this._lastNotificationError = "";
        this._lastNotificationCheckTime = checkedAt.toISOString();
        return candidates;
    }
}

if (typeof module !== "undefined" && module.exports) {
    module.exports = {
        buildNotificationCandidates: buildNotificationCandidates,
        canUseObsidianNotice: canUseObsidianNotice,
        getNotificationSettings: getNotificationSettings,
        recordNotificationDelivery: recordNotificationDelivery,
        pruneNotificationDelivery: pruneNotificationDelivery
    };
}
