// src/macos/notifications.js — In-app notification helpers and MacOSIntegration prototype methods
// Auto-generated by split script. Edit here, then run ./build-main.sh

function getNotificationSettings(options) {
    var opts = options || {};
    var lead = Number(opts.notificationLeadMinutes);
    if (!isFinite(lead) || lead < 1) lead = 10;
    if (lead > 1440) lead = 1440;
    return {
        notificationsEnabled: opts.notificationsEnabled === true,
        eventNotificationsEnabled: opts.eventNotificationsEnabled !== false,
        reminderNotificationsEnabled: opts.reminderNotificationsEnabled !== false,
        notificationLeadMinutes: lead
    };
}

function getNotificationItemId(type, item) {
    var rawId = item && item.id ? String(item.id) : "";
    if (!rawId) return "";
    return type + ":" + rawId;
}

function notificationWasDelivered(delivered, id) {
    return !!(delivered && id && delivered[id]);
}

function recordNotificationDelivery(delivered, id, now) {
    if (!delivered || !id) return;
    delivered[id] = (now || new Date()).toISOString();
}

function pruneNotificationDelivery(delivered, now) {
    if (!delivered) return;
    var cutoff = (now || new Date()).getTime() - 48 * 60 * 60 * 1000;
    Object.keys(delivered).forEach(function(id) {
        var t = new Date(delivered[id]).getTime();
        if (!isFinite(t) || t < cutoff) delete delivered[id];
    });
}

function buildNotificationCandidates(input) {
    var now = input && input.now ? input.now : new Date();
    var options = getNotificationSettings(input && input.options);
    var delivered = (input && input.delivered) || {};
    var events = (input && input.events) || [];
    var reminders = (input && input.reminders) || [];
    var candidates = [];

    if (!options.notificationsEnabled) return candidates;

    if (options.eventNotificationsEnabled) {
        var leadMs = options.notificationLeadMinutes * 60 * 1000;
        events.forEach(function(evt) {
            if (!evt || !evt.start) return;
            var isAllDay = evt.isAllDay !== undefined ? evt.isAllDay : evt.allday;
            if (isAllDay) return;
            var start = evt.start instanceof Date ? evt.start : new Date(evt.start);
            var diff = start.getTime() - now.getTime();
            if (!isFinite(diff) || diff <= 0 || diff > leadMs) return;
            var id = getNotificationItemId("event", evt);
            if (!id || notificationWasDelivered(delivered, id)) return;
            var minutes = Math.max(1, Math.ceil(diff / 60000));
            var title = evt.title || evt.summary || "Event";
            candidates.push({
                id: id,
                type: "event",
                itemId: evt.id,
                title: title,
                message: title + " starts in " + minutes + " minute" + (minutes === 1 ? "" : "s")
            });
        });
    }

    if (options.reminderNotificationsEnabled) {
        reminders.forEach(function(rem) {
            if (!rem || !rem.due || rem.completed) return;
            var due = rem.due instanceof Date ? rem.due : new Date(rem.due);
            var diff = due.getTime() - now.getTime();
            if (!isFinite(diff) || diff > 0) return;
            var id = getNotificationItemId("reminder", rem);
            if (!id || notificationWasDelivered(delivered, id)) return;
            var title = rem.title || rem.name || "Reminder";
            candidates.push({
                id: id,
                type: "reminder",
                itemId: rem.id,
                title: title,
                message: title + " is overdue"
            });
        });
    }

    return candidates;
}

function canUseObsidianNotice(obsidianRef) {
    return !!(obsidianRef && typeof obsidianRef.Notice === "function");
}

if (typeof MacOSIntegration !== "undefined") {
    MacOSIntegration.prototype.notifyDueItems = function(now) {
        var settings = getNotificationSettings(this.plugin.options || {});
        if (!settings.notificationsEnabled) {
            this._notificationStatus = "disabled";
            return [];
        }
        if (!canUseObsidianNotice(typeof obsidian !== "undefined" ? obsidian : null)) {
            this._notificationStatus = "unavailable";
            this._lastNotificationError = "Obsidian Notice API is unavailable";
            return [];
        }

        var checkedAt = now || new Date();
        pruneNotificationDelivery(this._deliveredNotifications, checkedAt);
        var candidates = buildNotificationCandidates({
            now: checkedAt,
            options: this.plugin.options || {},
            events: this.allEvents || [],
            reminders: this.allReminders || [],
            delivered: this._deliveredNotifications || {}
        });

        for (var i = 0; i < candidates.length; i++) {
            try {
                new obsidian.Notice(candidates[i].message, 8000);
                recordNotificationDelivery(this._deliveredNotifications, candidates[i].id, checkedAt);
            } catch (err) {
                this._notificationStatus = "error";
                this._lastNotificationError = err && err.message ? err.message : String(err);
                return candidates.slice(0, i);
            }
        }

        this._notificationStatus = "ok";
        this._lastNotificationError = "";
        this._lastNotificationCheckTime = checkedAt.toISOString();
        return candidates;
    }
}

if (typeof module !== "undefined" && module.exports) {
    module.exports = {
        buildNotificationCandidates: buildNotificationCandidates,
        canUseObsidianNotice: canUseObsidianNotice,
        getNotificationSettings: getNotificationSettings,
        recordNotificationDelivery: recordNotificationDelivery,
        pruneNotificationDelivery: pruneNotificationDelivery
    };
}
