// src/cache/schedule-cache.js — MacOSIntegration prototype methods
// Auto-generated by split script. Edit here, then run ./build-main.sh

MacOSIntegration.prototype.loadEventsFromCache = async function() {
        try {
            var raw = await this.plugin.readCacheFile('_eventsCache');
            if (raw && raw.events && raw.events.length > 0) {
                var events = [];
                for (var i = 0; i < raw.events.length; i++) {
                    var e = raw.events[i];
                    e.start = e._start ? new Date(e._start) : null;
                    e.end = e._end ? new Date(e._end) : null;
                    // Backward compat: migrate old field names to SPEC model
                    if (!e.title && e.summary) e.title = e.summary;
                    if (!e.calendarName && e.calendar) e.calendarName = e.calendar;
                    if (e.isAllDay === undefined && e.allday !== undefined) e.isAllDay = e.allday;
                    events.push(e);
                }
                this.allEvents = events;
                this._itemLookupCache = null;  // invalidate reverse index
                if (raw.colors) this.calendarColors = raw.colors;
                if (raw.cacheStart) this.cacheStart = window.moment(raw.cacheStart);
                if (raw.cacheEnd) this.cacheEnd = window.moment(raw.cacheEnd);
                this._cacheSavedAt = raw.savedAt || null;
                this.permissionState.calendar = 'granted';
                console.log("[Calendian] Loaded " + events.length + " events from disk cache (saved at " + (raw.savedAt || "unknown") + ")");
                return true;
            }
        } catch (e) {
            console.warn("[Calendian] Failed to load events from cache:", e.message);
        }
        return false;
    }

MacOSIntegration.prototype.isCacheFresh = function() {
        if (!this._cacheSavedAt) return false;
        // If JXA is already running, consider cache "fresh enough" — don't stack calls
        if (this._refreshRunning) return true;
        try {
            var savedTime = new Date(this._cacheSavedAt).getTime();
            var ageMs = Date.now() - savedTime;
            // Use 2x the refresh interval, minimum 15 minutes, to avoid hammering Calendar.app
            var intervalMin = Math.max(15, (this.plugin.options?.refreshIntervalMinutes || 5) * 2);
            return ageMs < (intervalMin * 60 * 1000);
        } catch (e) { return false; }
    }

MacOSIntegration.prototype.saveEventsToCache = async function() {
        try {
            var events = [];
            for (var i = 0; i < this.allEvents.length; i++) {
                var e = this.allEvents[i];
                events.push({
                    id: e.id, source: e.source,
                    title: e.title || e.summary || "",
                    _start: e.start ? e.start.toISOString() : null,
                    _end: e.end ? e.end.toISOString() : null,
                    calendarName: e.calendarName || e.calendar || "",
                    calendarId: e.calendarId || "",
                    isAllDay: e.isAllDay !== undefined ? e.isAllDay : (e.allday || false),
                    location: e.location || "", url: e.url || "",
                    notes: e.notes || "", isRecurring: e.isRecurring || false,
                    recurrenceSummary: e.recurrenceSummary || "",
                    isDisplayOnly: e.isDisplayOnly || false
                });
            }
            var cache = {
                events: events,
                colors: this.calendarColors,
                cacheStart: this.cacheStart ? this.cacheStart.format() : null,
                cacheEnd: this.cacheEnd ? this.cacheEnd.format() : null,
                savedAt: new Date().toISOString()
            };
            await this.plugin.writeCacheFile('_eventsCache', cache);
        } catch (e) {
            console.warn("[Calendian] Failed to save events to cache:", e.message);
        }
    }

MacOSIntegration.prototype.saveRemindersToCache = async function() {
        try {
            var reminders = [];
            for (var i = 0; i < this.allReminders.length; i++) {
                var r = this.allReminders[i];
                reminders.push({
                    id: r.id, source: r.source,
                    title: r.title || r.name || "",
                    _due: r.due ? r.due.toISOString() : null,
                    dueDate: r.dueDate || "",
                    dueTime: reminderHasDueTime(r) ? (r.dueTime || "") : "",
                    hasDueTime: reminderHasDueTime(r),
                    listName: r.listName || r.list || "",
                    listId: r.listId || "",
                    priority: r.priority || "none",
                    completed: r.completed || false,
                    notes: r.notes || "",
                    isDisplayOnly: r.isDisplayOnly || false
                });
            }
            var cache = {
                reminders: reminders,
                savedAt: new Date().toISOString()
            };
            await this.plugin.writeCacheFile('_remindersCache', cache);
        } catch (e) {
            console.warn("[Calendian] Failed to save reminders to cache:", e.message);
        }
    }

MacOSIntegration.prototype.loadRemindersFromCache = async function() {
        try {
            var raw = await this.plugin.readCacheFile('_remindersCache');
            if (raw && raw.reminders && raw.reminders.length > 0) {
                var reminders = [];
                for (var i = 0; i < raw.reminders.length; i++) {
                    var r = raw.reminders[i];
                    r.due = r._due ? new Date(r._due) : null;
                    // Backward compat: migrate old field names
                    if (!r.title && r.name) r.title = r.name;
                    if (!r.listName && r.list) r.listName = r.list;
                    reminders.push(normalizeReminderTemporalFields(r));
                }
                this.allReminders = reminders;
                this._itemLookupCache = null;  // invalidate reverse index
                this.permissionState.reminders = 'granted';

                // Debug: check for duplicates
                const ids = reminders.map(r => r.id);
                const uniqueIds = new Set(ids);
                if (ids.length !== uniqueIds.size) {
                    console.warn("[Calendian] WARNING: Found " + (ids.length - uniqueIds.size) + " duplicate reminder IDs in loadRemindersFromCache");
                }
                console.log("[Calendian] Loaded " + reminders.length + " reminders from disk cache (" + uniqueIds.size + " unique IDs)");
                return true;
            }
        } catch (e) {
            console.warn("[Calendian] Failed to load reminders from cache:", e.message);
        }
        return false;
    }

MacOSIntegration.prototype.preloadAll = async function() {
        this.isLoading.calendar = true;
        var now = window.moment();
        this.cacheStart = now.clone().subtract(6, 'months').startOf('month');
        this.cacheEnd = now.clone().add(6, 'months').endOf('month');
        var fromISO = this.cacheStart.toISOString().replace(/\.\d{3}Z$/, 'Z');
        var toISO = this.cacheEnd.toISOString().replace(/\.\d{3}Z$/, 'Z');

        var opts = this.plugin.options || {};
        var filterIds = opts.selectedCalendarIds || [];

        try {
            var startMs = Date.now();
            // Always fetch all events from helper — JS-side filtering in getEventsForDate
            // handles name/ID matching. Passing names to helper fails because helper
            // matches against UUIDs, not display names. (REQ-FILTER-001)
            var args = ['events', fromISO, toISO];
            // NOTE: filterIds intentionally NOT passed to helper — see above
            var rawEvents = await this.execHelper(args);
            console.log("[Calendian] EventKit events completed in " + (Date.now() - startMs) + "ms, " + rawEvents.length + " events");

            // Map to internal model + collect colors
            var colors = {};
            var events = [];
            for (var i = 0; i < rawEvents.length; i++) {
                var e = rawEvents[i];
                if (e.calendarColor) { colors[e.calendarName] = e.calendarColor; }
                events.push({
                    id: e.id,
                    source: "macos-calendar",
                    title: e.title || "",
                    start: e.start ? new Date(e.start) : null,
                    end: e.end ? new Date(e.end) : null,
                    calendarName: e.calendarName || "",
                    calendarId: e.calendarId || "",
                    calendarColor: e.calendarColor || "",
                    isAllDay: e.isAllDay || false,
                    isRecurring: e.isRecurring || false,
                    recurrenceSummary: e.recurrenceSummary || "",
                    location: e.location || "",
                    url: e.url || "",
                    notes: e.notes || "",
                    attendees: e.attendees || [],
                    accountName: e.accountName || "",
                    isDisplayOnly: !e.id  // REQ-DATA-003: mark items without a stable EventKit identifier
                });
            }
            this.calendarColors = colors;
            this.allEvents = events;
            this._itemLookupCache = null;  // invalidate reverse index
            this.permissionState.calendar = 'granted';
            this.lastError.calendar = null;
            this.sourceCounts.calendars = Object.keys(colors).length;
            this.saveEventsToCache();
        } catch (err) {
            console.error("[Calendian] Failed to preload events:", err.error?.message || err.stderr, "stderr:", err.stderr);
            var errorType = this.classifyError(err);
            this.permissionState.calendar = errorType;
            this.lastError.calendar = { type: errorType, message: (err.stderr || err.error?.message || 'Unknown error'), timestamp: new Date().toISOString() };
            if (errorType === 'permission_denied') { this.allEvents = []; this._itemLookupCache = null; }
        }
        this.isLoading.calendar = false;
    }

MacOSIntegration.prototype.preloadReminders = async function() {
        this.isLoading.reminders = true;
        var now = window.moment();
        var fromISO = now.clone().subtract(6, 'months').startOf('month').toISOString().replace(/\.\d{3}Z$/, 'Z');
        var toISO = now.clone().add(6, 'months').endOf('month').toISOString().replace(/\.\d{3}Z$/, 'Z');

        var opts = this.plugin.options || {};
        var filterIds = opts.selectedReminderListIds || [];

        try {
            // Always fetch all reminders from helper — JS-side filtering in getRemindersForDate
            // handles name/ID matching. (REQ-FILTER-001)
            var args = ['reminders', fromISO, toISO];
            // NOTE: filterIds intentionally NOT passed to helper
            var rawReminders = await this.execHelper(args);

            var reminders = [];
            for (var i = 0; i < rawReminders.length; i++) {
                var r = rawReminders[i];
                reminders.push(normalizeReminderTemporalFields({
                    id: r.id || "",
                    source: "macos-reminders",
                    title: r.title || "",
                    dueDate: r.dueDate || "",
                    due: r.dueDate ? new Date(r.dueDate) : null,
                    dueTime: r.dueTime || "",
                    hasDueTime: !!r.dueTime,
                    listName: r.listName || "",
                    listId: r.listId || "",
                    priority: r.priority || "none",
                    completed: r.completed || false,
                    notes: r.notes || "",
                    parentId: r.parentId || "",
                    isDisplayOnly: !r.id
                }));
            }
            // Fetch no-due-date reminders and merge
            try {
                // Same as above: don't pass filter names to helper (REQ-FILTER-001)
                var nodateArgs = ['reminders-nodate'];
                var rawNoDate = await this.execHelper(nodateArgs);
                for (var j = 0; j < rawNoDate.length; j++) {
                    var nd = rawNoDate[j];
                    reminders.push(normalizeReminderTemporalFields({
                        id: nd.id || "",
                        source: "macos-reminders",
                        title: nd.title || "",
                        dueDate: "",
                        due: null,
                        dueTime: "",
                        hasDueTime: false,
                        listName: nd.listName || "",
                        listId: nd.listId || "",
                        priority: nd.priority || "none",
                        completed: nd.completed || false,
                        notes: nd.notes || "",
                        parentId: nd.parentId || "",
                        isDisplayOnly: !nd.id
                    }));
                }
            } catch (nodateErr) {
                console.warn("[Calendian] No-date reminders fetch failed:", nodateErr.stderr || nodateErr.message);
            }
            this.allReminders = reminders;
            this._itemLookupCache = null;  // invalidate reverse index
            this.permissionState.reminders = 'granted';
            this.lastError.reminders = null;
            this.sourceCounts.reminderLists = this.countReminderLists(reminders);

            // Debug: check for duplicates
            const ids = reminders.map(r => r.id);
            const uniqueIds = new Set(ids);
            if (ids.length !== uniqueIds.size) {
                console.warn("[Calendian] WARNING: Found " + (ids.length - uniqueIds.size) + " duplicate reminder IDs in preloadReminders");
            }
            console.log("[Calendian] Preloaded " + reminders.length + " reminders (" + uniqueIds.size + " unique IDs)");

            this.saveRemindersToCache();
        } catch (err) {
            console.error("[Calendian] Failed to preload reminders:", err.error?.message || err.stderr);
            var errorType = this.classifyError(err);
            this.permissionState.reminders = errorType;
            this.lastError.reminders = { type: errorType, message: (err.stderr || err.error?.message || 'Unknown error'), timestamp: new Date().toISOString() };
            if (errorType === 'permission_denied') { this.allReminders = []; this._itemLookupCache = null; }
        }
        this.isLoading.reminders = false;
    }

MacOSIntegration.prototype.getEventsForDate = function(date) {
        var d = date.toDate();
        var y = d.getFullYear(), m = d.getMonth(), day = d.getDate();
        var dayStart = new Date(y, m, day, 0, 0, 0);
        var dayEnd = new Date(y, m, day, 23, 59, 59);
        var filterIds = (this.plugin.options && this.plugin.options.selectedCalendarIds) || [];
        var calColors = this.calendarColors || {};
        return this.allEvents.filter(function(e) {
            if (!e.start) return false;
            // Apply calendar source filter by compound ID (name|||color) or plain ID
            if (filterIds.length > 0) {
                var eName = e.calendarName || e.calendar || "";
                var eColor = calColors[eName] || "";
                var eCompoundId = eName + "|||" + eColor;
                var eId = e.calendarId || e.id || "";
                var matched = filterIds.includes(eCompoundId) || filterIds.includes(eId) || filterIds.includes(eName);
                if (!matched) return false;
            }
            // Check if event overlaps with this day [dayStart, dayEnd]
            var evtStart = e.start;
            var evtEnd = e.end || e.start;
            // Event overlaps day if evtStart <= dayEnd AND evtEnd >= dayStart
            return evtStart <= dayEnd && evtEnd >= dayStart;
        }).sort(function(a, b) {
            var aAllDay = a.isAllDay !== undefined ? a.isAllDay : a.allday;
            var bAllDay = b.isAllDay !== undefined ? b.isAllDay : b.allday;
            if (aAllDay && !bAllDay) return -1;
            if (!aAllDay && bAllDay) return 1;
            if (!a.start || !b.start) return 0;
            return a.start.getTime() - b.start.getTime();
        });
    }

MacOSIntegration.prototype.getRemindersForDate = function(date) {
        var opts = this.plugin.options || {};
        var filterIds = opts.selectedReminderListIds || [];

        var d = date.toDate();
        var y = d.getFullYear(), m = d.getMonth(), day = d.getDate();
        var dayStart = new Date(y, m, day, 0, 0, 0, 0);
        var dayEnd = new Date(y, m, day, 23, 59, 59, 999);

        // Determine if selected date is today
        var now = new Date();
        var todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0);
        var isToday = dayStart.getTime() === todayStart.getTime();

        var start, end;
        if (isToday) {
            // Today view: include overdue (from far past) + today + upcoming N days
            start = new Date(2000, 0, 1, 0, 0, 0);
            var upcomingDays = opts.upcomingReminderDays != null ? opts.upcomingReminderDays : 7;
            if (upcomingDays === 0) {
                end = new Date(2099, 11, 31, 23, 59, 59, 999); // all future
            } else {
                end = new Date(now.getFullYear(), now.getMonth(), now.getDate() + upcomingDays, 23, 59, 59, 999);
            }
        } else {
            // Non-today: only reminders due on that exact day
            start = dayStart;
            end = dayEnd;
        }

        return this.allReminders.filter(function(r) {
            // Apply reminder list filter by ID (primary) or name (fallback)
            if (filterIds.length > 0) {
                var rId = r.listId || r.id || "";
                var rName = r.listName || r.list || "";
                var matched = filterIds.includes(rId) || filterIds.includes(rName);
                if (!matched) return false;
            }
            // Reminders with no due date are handled separately (see renderRemindersSection)
            if (!r.due) return false;
            return r.due >= start && r.due <= end;
        });
    }

MacOSIntegration.prototype.getNoDateReminders = function() {
        var opts = this.plugin.options || {};
        var filterIds = opts.selectedReminderListIds || [];
        return this.allReminders.filter(function(r) {
            if (filterIds.length > 0) {
                var rId = r.listId || r.id || "";
                var rName = r.listName || r.list || "";
                var matched = filterIds.includes(rId) || filterIds.includes(rName);
                if (!matched) return false;
            }
            return !r.due;
        });
    }

MacOSIntegration.prototype.parseEvents = function(raw) {
        if (!raw) return [];
        return raw.split("\n").filter(Boolean).reduce(function(acc, line) {
            try {
                const parts = line.split("|||");
                // JXA output format: summary|startDate|endDate|calendarName|allday|uid
                var evt = {
                    id: parts[5] || ("evt-" + encodeURIComponent(parts[0] || "untitled") + "-" + (parts[1] || "0")),
                    source: "macos-calendar",
                    title: parts[0] || "",
                    start: parts[1] ? new Date(parts[1]) : null,
                    end: parts[2] ? new Date(parts[2]) : null,
                    calendarName: parts[3] || "",
                    calendarId: parts[3] || "",
                    calendarColor: "",
                    isAllDay: parts[4] === "1",
                    isRecurring: false,
                    recurrenceSummary: "",
                    location: "",
                    url: "",
                    notes: "",
                    attendees: [],
                    alarms: []
                };
                if (evt.title || evt.start) {
                    acc.push(evt);
                }
            } catch (e) {
                console.warn("[Calendian] Skipped unparseable event record:", line.substring(0, 80));
            }
            return acc;
        }, []);
    }

MacOSIntegration.prototype.parseReminders = function(raw) {
        if (!raw) return [];
        // REQ-DATA-005: Isolate parse failures to individual records
        var listNames = {};
        return raw.split("\n").filter(Boolean).reduce(function(acc, line) {
            try {
                const parts = line.split("|||");
                var listName = parts[2] || "";
                if (listName && !listNames[listName]) listNames[listName] = true;
                var priority = "none";
                if (parts[4] && parts[4] !== "none") {
                    var p = parseInt(parts[4], 10);
                    if (!isNaN(p)) {
                        if (p <= 500) priority = "high";
                        else if (p <= 700) priority = "medium";
                        else priority = "low";
                    }
                }
                var rem = normalizeReminderTemporalFields({
                    id: parts[3] || ("rem-" + (parts[0] || "unknown") + "-" + (parts[2] || "n/a")),
                    source: "macos-reminders",
                    title: parts[0] || "",
                    dueDate: parts[1] || "",
                    due: parts[1] ? new Date(parts[1]) : null,
                    dueTime: "",
                    hasDueTime: false,
                    listName: listName,
                    listId: listName,
                    priority: priority,
                    completed: parts[5] === "1",
                    notes: parts[6] || "",
                    parentId: ""
                });
                if (rem.title) {
                    acc.push(rem);
                }
            } catch (e) {
                // REQ-DATA-005: Skip malformed record
                console.warn("[Calendian] Skipped unparseable reminder record:", line.substring(0, 80));
            }
            return acc;
        }, []);
    }

MacOSIntegration.prototype.countReminderLists = function(reminders) {
        var lists = {};
        for (var i = 0; i < reminders.length; i++) {
            var ln = reminders[i].listName || reminders[i].list || "";
            if (ln) lists[ln] = true;
        }
        return Object.keys(lists).length;
    }
